version: "3.3"

networks:
  cassandra_backend:
    driver: bridge


services:
  cassandra-seed:
    #image: "cassandra:4.0"
    build:
        context: cass
   # optionally expose to outside network
    ports:
       - "7000:7000"
       - "7199:7199"
       - "9042:9042"
       - "9160:9160"
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
    volumes: #Share the HOME directory to allow using the same paths as in the host machine
      - $HOME:$HOME
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - cassandra_backend

  cassandra:
    #image: "cassandra:4.0"
    build:
      context: cass
    depends_on:
      - cassandra-seed
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
    healthcheck:
      test: ["CMD-SHELL", "nodetool", "status"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - cassandra_backend

  hecuba:
    build:
      context: .
    volumes: #Share the HOME directory to allow using the same paths as in the host machine
      - $HOME:$HOME
    depends_on:
      - cassandra-seed
