sudo: false
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8-dev'
services:
  - docker

env:
  matrix:
    - TEST_CASSANDRA_VERSION=3.11.4

stages:
  - test
  - build_wheel_manylinux2010
  - build_wheel_manylinux1

before_install:
  - source .travis/install_openjdk8.sh

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - cmake
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy

# command to run tests
script:
  #- nosetests --with-coverage -v -s hecuba_py/tests/*.py
  #- nosetests --with-coverage -v -s hecuba_py/tests/withcassandra
  - nosetests --with-coverage -v -s storage/cql_iface/tests/api_tests.py

# Push the results back to codecov
after_success:
  - codecov

