sudo: false
dist: xenial
language: python
services:
  - docker

stages:
  - test_integration

before_install:
  - source .travis/install_openjdk8.sh

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - cmake
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy

# command to run tests

jobs:
  include:
    - stage: test_integration
      sudo: required
      install:
        - docker build -t hecompss:0.1 dockerfiles/compss_integration
      script:
       - docker network create --driver bridge hecompss_bridge
       - CASSANDRA_ID=$(docker run --rm --network=hecompss_bridge -d  cassandra)
       - sleep 30
       - CASSANDRA_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CASSANDRA_ID})
       - docker run --rm -it --env CONTACT_NAMES=${CASSANDRA_IP} --network=hecompss_bridge hecompss:0.1docker run --rm -it hecompss:0.1
