sudo: false
dist: trusty
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install --user
# command to run tests
script:
  - nosetests tests/*.py
  - nosetests tests/withcassandra

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - oracle-java8-installer
      - cmake
      - python-dev
      - lipython-dev
      - gcc-4.8
      - libtool
      - python-numpy
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
before_install:
  - java -version
  -  wget http://ftp.cixug.es/apache/cassandra/3.11.1/apache-cassandra-3.11.1-bin.tar.gz && tar -xzf apache-cassandra-3.11.1-bin.tar.gz && apache-cassandra-3.11.1/bin/cassandra & disown
