sudo: required
language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
before_install:
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://apache.rediris.es/cassandra/3.0.10/apache-cassandra-3.0.10-bin.tar.gz && tar -xzf apache-cassandra-3.0.10-bin.tar.gz && sudo sh apache-cassandra-3.0.10/bin/cassandra & disown
