sudo: false
dist: trusty
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install --user
# command to run tests

jdk:
  - oraclejdk8
jobs:
  include:
    - stage: testing
      env:
        - TEST_CASSANDRA_VERSION=3.11.4
      script:
        - nosetests --with-coverage -v -s hecuba_py/tests/*.py
        - nosetests --with-coverage -v -s hecuba_py/tests/withcassandra
    - stage: building-manylinux2010
      sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64  PLAT=manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/.travis/build-wheels.sh
        - python -c "import hfetch"
        - ls wheelhouse/
    - stage: building-manylinux1_x86_64
      sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64  PLAT=manylinux1_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/.travis/build-wheels.sh
        - python -c "import hfetch"
        - ls wheelhouse/

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - cmake3
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy

env.global:
  - PYTHONPATH=/home/travis/.local/lib/python3.6/site-packages/
before_install:
  - export CFLAGS='-std=c++11'
  - java -version

# Push the results back to codecov
after_success:
  - codecov
