sudo: false
dist: trusty
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install --user
# command to run tests
script:
  - nosetests -v -s hecuba_py/tests/*.py
  - nosetests -v -s hecuba_py/tests/withcassandra
jdk:
  - oraclejdk8
#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - cmake3
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy
env:
  - TEST_CASSANDRA_VERSION=3.11.4
  - TEST_CASSANDRA_VERSION=3.0.18
  - TEST_CASSANDRA_VERSION=2.2.14
env.global:
  - PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
before_install:
  - export PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
  - export CFLAGS='-std=c++11'
  - java -version