sudo: false
dist: trusty
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install --user
# command to run tests
script:
  - nosetests -v -s hecuba_py/tests/*.py
  - nosetests -v -s hecuba_py/tests/withcassandra
jdk:
  - oraclejdk8
#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - cmake3
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy
env:
  global:
    - PYTHONPATH=/home/travis/.local/lib/python3.6/site-packages/
before_install:
  - export PYTHONPATH=/home/travis/.local/lib/python3.6/site-packages/
  - export CFLAGS='-std=c++11'
  - java -version
  - wget http://archive.apache.org/dist/cassandra/3.11.3/apache-cassandra-3.11.3-bin.tar.gz && tar -xzf apache-cassandra-3.11.3-bin.tar.gz && apache-cassandra-3.11.3/bin/cassandra & disown
