language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

#caches dependencies
cache: bundler
script:
  - jdk_switcher use oraclejdk8
before_install:
  - wget http://apache.rediris.es/cassandra/3.0.10/apache-cassandra-3.0.10-bin.tar.gz && tar -xvzf apache-cassandra-3.0.10-bin.tar.gz && apache-cassandra-3.0.10/bin/cassandra