sudo: false
dist: trusty
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install --user
# command to run tests
script:
  - nosetests -v -s hecuba_py/tests/*.py
  - nosetests -v -s hecuba_py/tests/withcassandra
  - nosetests -v -s hecuba_core/tests/py_interface

#caches dependencies
cache: bundler
addons:
  apt:
    packages:
      - oracle-java8-installer
      - cmake3
      - python-dev
      - libpython-dev
      - gcc-4.8
      - libtool
      - python-numpy
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
  - export CFLAGS='-std=c++11'
  - java -version
  - wget http://archive.apache.org/dist/cassandra/3.11.3/apache-cassandra-3.11.3-bin.tar.gz && tar -xzf apache-cassandra-3.11.3-bin.tar.gz && apache-cassandra-3.11.3/bin/cassandra & disown
